env:
  global:
    - CODECLIMATE_REPO_TOKEN=28c86855122bc245dd440cd9e39ba32a11eab19562afd4aafa0cfcdb3afdc26f
language: node_js
node_js:
  - stable
cache: yarn
script:
  - yarn lint && yarn test
  - yarn codecov
notifications:
  email: false
